meta-dial-turn-v2:
  algorithm: ppo
  algo_params:
    batch_size: 200
    learning_rate: 0.0001
    n_steps: 200
    total_timesteps: 2.e+7
    policy: MlpPolicy
    policy_type: on_policy
    policy_kwargs:
      activation_fn: tanh
      pi: 256
      vf: 256
  env_params:
    env_name: modified_envs
    num_envs: 10
    wrapper: None
  eval_env:
    n_eval_episode: 10
    eval_freq: 2000


Meta-v2:
  algorithm: ppo
  algo_params:
    batch_size: 200
    learning_rate: 0.0001
    n_steps: 200
    total_timesteps: 2.e+7
    policy: MlpPolicy
    policy_type: on_policy
    policy_kwargs:
      activation_fn: tanh
      pi: 256
      vf: 256
  env_params:
    env_name: modified_envs
    num_envs: 10
    wrapper: None
  eval_env:
    n_eval_episode: 10
    eval_freq: 2000
